sources:
  - include: ./sources.d/.*.yaml
  - uri: unix:/srv/iplb/11622/chroot/run/proc_1.sock
    labels:
      allnics: '|ib8368-ovh|'
      iplb: '5405276'
      offer: 'legacy'
      ovh.bu: 'none'
      slot: '11622'
      socket: '1'
      zone: 'gra'
  - uri: unix:/srv/iplb/11622/chroot/run/proc_2.sock
    labels:
      allnics: '|ib8368-ovh|'
      iplb: '5405276'
      offer: 'legacy'
      ovh.bu: 'none'
      slot: '11622'
      socket: '2'
      zone: 'gra'

metrics:
  - qcur
  - qmax
  - scur
  - smax
  - slim
  - stot
  - bin
  - bout
  - dreq
  - dresp
  - ereq
  - econ
  - eresp
  - wretr
  - wredis
  - chkfail
  - chkdown
  - downtime
  - qlimit
  - rate
  - rate_lim
  - rate_max
  - hrsp_1xx
  - hrsp_2xx
  - hrsp_3xx
  - hrsp_4xx
  - hrsp_5xx
  - hrsp_other
  - req_rate
  - req_rate_max
  - req_tot
  - cli_abrt
  - srv_abrt
